//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedestrianVolume
    {
        public int Id { get; set; }
        public Nullable<double> Sensor_ID { get; set; }
        public string Day { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> HoursCount { get; set; }
        public string Coordinates { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
